# Generated by Django 4.0.3 on 2023-08-16 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_shopping_car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_product_shopping_car', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='point_transaction',
            name='purchase_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_detail_point_transaction', to='Movement.purchase_detail', verbose_name='Detalle de compra'),
        ),
        migrations.AddField(
            model_name='main_purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_main_purchase', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='custom_order',
            name='product_shopping_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_shopping_car_custom_order', to='Movement.product_shopping_car', verbose_name='Carrito de compra'),
        ),
        migrations.AddField(
            model_name='custom_order',
            name='purchase_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_detail_custom_order', to='Movement.purchase_detail', verbose_name='Detalle de compra'),
        ),
    ]
