# Generated by Django 4.0.3 on 2023-08-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movement', '0003_alter_custom_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_shopping_car',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='purchase_detail',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='purchase_detail',
            name='status',
            field=models.CharField(choices=[('waiting', 'En espera'), ('success', 'Realizada')], default='', max_length=50, verbose_name='Estado de orden'),
        ),
        migrations.DeleteModel(
            name='Custom_Order',
        ),
    ]
