# Generated by Django 4.2.4 on 2023-08-21 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_product_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movement', '0004_product_shopping_car_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('description', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Descripción')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_shopping_car', to='Inventory.product', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_shopping_car', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carrito de compra',
                'verbose_name_plural': 'Carritos de compras',
                'ordering': ['user', 'product'],
            },
        ),
        migrations.DeleteModel(
            name='Product_Shopping_Car',
        ),
    ]
