# Generated by Django 4.0.3 on 2023-08-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movement', '0005_shopping_car_delete_product_shopping_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_purchase',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
    ]
