# Generated by Django 4.0.3 on 2023-08-16 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identification', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Identificación')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Número telefónico')),
                ('point', models.IntegerField(default=0, verbose_name='Puntos')),
                ('salary', models.FloatField(blank=True, default=0, null=True, verbose_name='Salario')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('entrance_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('inactive_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de inactivación')),
                ('is_active', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=True, verbose_name='Está activo')),
                ('is_staff', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False, verbose_name='Es staff')),
                ('is_superuser', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False, verbose_name='Es admin')),
                ('charge', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_user', to='User.charge', verbose_name='Cargo de usuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['last_name', 'first_name', 'identification'],
            },
        ),
    ]
