# Generated by Django 4.2.4 on 2023-08-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_userprofile_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='salary',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Salario'),
        ),
    ]
