# Generated by Django 4.0.3 on 2023-08-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_userprofile_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default='2023-09-08', verbose_name='Fecha de nacimiento'),
            preserve_default=False,
        ),
    ]
