# Generated by Django 4.0.3 on 2023-08-16 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(default='', max_length=300, verbose_name='Descripción')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Question_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, default=None, null=True, verbose_name='Puntuación')),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Descripción')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_question_answer', to='Inventory.product', verbose_name='Producto')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_question_answer', to='Interaction.question', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Cargos',
            },
        ),
    ]
