# Generated by Django 4.0.3 on 2023-08-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interaction', '0002_alter_question_answer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='with_product',
            field=models.BooleanField(default=True, verbose_name='Pregunta con producto'),
        ),
    ]
