# Generated by Django 4.0.3 on 2023-08-16 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(default='', max_length=250, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('money_unit_price', models.FloatField(default=0, verbose_name='Valor monetario unitario')),
                ('point_unit_price', models.IntegerField(default=0, verbose_name='Valor de puntos unitario')),
                ('description', models.CharField(default='', max_length=250, verbose_name='description')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('weight', models.FloatField(blank=True, default=None, null=True, verbose_name='Peso')),
                ('measure_unit', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Unidad de medida')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='Inventory.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name', 'pk'],
            },
        ),
    ]
