# Generated by Django 4.2.4 on 2023-08-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=250, verbose_name='Descripción'),
        ),
    ]
