# Generated by Django 4.0.3 on 2023-08-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='product',
            name='image_product',
            field=models.FileField(blank=True, null=True, upload_to='inventory/products/'),
        ),
    ]
